
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'comandoAND BATCH CANCELAR COLON COMMA CONSULTA DATA DATE DEF DISPONIBILIDADE ELSE EQUALS ESPACO FALSE FILTRO GREATER GREATER_EQUAL HORA_FIM HORA_INICIO ID IF LESS LESS_EQUAL LPAREN NEWLINE NOT NOT_EQUALS NUMBER OR PERIODO RESERVAR RESERVA_ID RPAREN STRING TIME TIPO TRUE UTILIZADORES\ncomando : reserva\n        | cancelamento\n        | consulta\n        | disponibilidade\n        | batch\n        | definicao\n        | if_statement\n\nreserva : RESERVAR COLON TIPO COLON ID ESPACO COLON STRING DATA COLON DATE HORA_INICIO COLON TIME HORA_FIM COLON TIME\n\ncancelamento : CANCELAR COLON RESERVA_ID COLON NUMBER\n\nconsulta : CONSULTA COLON TIPO COLON ID PERIODO COLON DATE FILTRO COLON ID\n\ndisponibilidade : DISPONIBILIDADE COLON TIPO COLON ID DATA COLON DATE HORA_INICIO COLON TIME HORA_FIM COLON TIME\n\nbatch : BATCH COLON lista_comandos\n\nlista_comandos : comando_batch comando_batch\n\nlista_comandos : lista_comandos comando_batch\n\ncomando_batch : reserva\n              | cancelamento\n              | consulta\n              | disponibilidade\n\ndefinicao : DEF ID\n\nif_statement : IF expressao ELSE ID\n\nexpressao : NOT expressao\n\nexpressao : ID EQUALS ID\n          | ID GREATER NUMBER\n          | ID LESS NUMBER\n          | ID GREATER_EQUAL NUMBER\n          | ID LESS_EQUAL NUMBER\n\nexpressao : expressao AND expressao\n          | expressao OR expressao\n'
    
_lr_action_items = {'RESERVAR':([0,20,29,30,31,32,33,34,48,49,59,78,85,88,],[9,9,9,9,-15,-16,-17,-18,-14,-13,-9,-10,-11,-8,]),'CANCELAR':([0,20,29,30,31,32,33,34,48,49,59,78,85,88,],[10,10,10,10,-15,-16,-17,-18,-14,-13,-9,-10,-11,-8,]),'CONSULTA':([0,20,29,30,31,32,33,34,48,49,59,78,85,88,],[11,11,11,11,-15,-16,-17,-18,-14,-13,-9,-10,-11,-8,]),'DISPONIBILIDADE':([0,20,29,30,31,32,33,34,48,49,59,78,85,88,],[12,12,12,12,-15,-16,-17,-18,-14,-13,-9,-10,-11,-8,]),'BATCH':([0,],[13,]),'DEF':([0,],[14,]),'IF':([0,],[15,]),'$end':([1,2,3,4,5,6,7,8,21,29,31,32,33,34,48,49,50,59,78,85,88,],[0,-1,-2,-3,-4,-5,-6,-7,-19,-12,-15,-16,-17,-18,-14,-13,-20,-9,-10,-11,-8,]),'COLON':([9,10,11,12,13,25,26,27,28,62,63,64,71,72,73,80,81,86,],[16,17,18,19,20,44,45,46,47,65,66,67,74,75,76,82,83,87,]),'ID':([14,15,24,35,36,37,38,44,46,47,75,],[21,23,23,50,23,23,53,58,60,61,78,]),'NOT':([15,24,36,37,],[24,24,24,24,]),'TIPO':([16,18,19,],[25,27,28,]),'RESERVA_ID':([17,],[26,]),'ELSE':([22,43,51,52,53,54,55,56,57,],[35,-21,-27,-28,-22,-23,-24,-25,-26,]),'AND':([22,43,51,52,53,54,55,56,57,],[36,36,36,36,-22,-23,-24,-25,-26,]),'OR':([22,43,51,52,53,54,55,56,57,],[37,37,37,37,-22,-23,-24,-25,-26,]),'EQUALS':([23,],[38,]),'GREATER':([23,],[39,]),'LESS':([23,],[40,]),'GREATER_EQUAL':([23,],[41,]),'LESS_EQUAL':([23,],[42,]),'NUMBER':([39,40,41,42,45,],[54,55,56,57,59,]),'ESPACO':([58,],[62,]),'PERIODO':([60,],[63,]),'DATA':([61,68,],[64,71,]),'STRING':([65,],[68,]),'DATE':([66,67,74,],[69,70,77,]),'FILTRO':([69,],[72,]),'HORA_INICIO':([70,77,],[73,80,]),'TIME':([76,82,83,87,],[79,84,85,88,]),'HORA_FIM':([79,84,],[81,86,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'comando':([0,],[1,]),'reserva':([0,20,29,30,],[2,31,31,31,]),'cancelamento':([0,20,29,30,],[3,32,32,32,]),'consulta':([0,20,29,30,],[4,33,33,33,]),'disponibilidade':([0,20,29,30,],[5,34,34,34,]),'batch':([0,],[6,]),'definicao':([0,],[7,]),'if_statement':([0,],[8,]),'expressao':([15,24,36,37,],[22,43,51,52,]),'lista_comandos':([20,],[29,]),'comando_batch':([20,29,30,],[30,48,49,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> comando","S'",1,None,None,None),
  ('comando -> reserva','comando',1,'p_comando','parser.py',8),
  ('comando -> cancelamento','comando',1,'p_comando','parser.py',9),
  ('comando -> consulta','comando',1,'p_comando','parser.py',10),
  ('comando -> disponibilidade','comando',1,'p_comando','parser.py',11),
  ('comando -> batch','comando',1,'p_comando','parser.py',12),
  ('comando -> definicao','comando',1,'p_comando','parser.py',13),
  ('comando -> if_statement','comando',1,'p_comando','parser.py',14),
  ('reserva -> RESERVAR COLON TIPO COLON ID ESPACO COLON STRING DATA COLON DATE HORA_INICIO COLON TIME HORA_FIM COLON TIME','reserva',17,'p_reserva','parser.py',20),
  ('cancelamento -> CANCELAR COLON RESERVA_ID COLON NUMBER','cancelamento',5,'p_cancelamento','parser.py',45),
  ('consulta -> CONSULTA COLON TIPO COLON ID PERIODO COLON DATE FILTRO COLON ID','consulta',11,'p_consulta','parser.py',55),
  ('disponibilidade -> DISPONIBILIDADE COLON TIPO COLON ID DATA COLON DATE HORA_INICIO COLON TIME HORA_FIM COLON TIME','disponibilidade',14,'p_disponibilidade','parser.py',67),
  ('batch -> BATCH COLON lista_comandos','batch',3,'p_batch','parser.py',80),
  ('lista_comandos -> comando_batch comando_batch','lista_comandos',2,'p_lista_comandos_base','parser.py',90),
  ('lista_comandos -> lista_comandos comando_batch','lista_comandos',2,'p_lista_comandos_rec','parser.py',96),
  ('comando_batch -> reserva','comando_batch',1,'p_comando_batch','parser.py',103),
  ('comando_batch -> cancelamento','comando_batch',1,'p_comando_batch','parser.py',104),
  ('comando_batch -> consulta','comando_batch',1,'p_comando_batch','parser.py',105),
  ('comando_batch -> disponibilidade','comando_batch',1,'p_comando_batch','parser.py',106),
  ('definicao -> DEF ID','definicao',2,'p_definicao','parser.py',112),
  ('if_statement -> IF expressao ELSE ID','if_statement',4,'p_if','parser.py',122),
  ('expressao -> NOT expressao','expressao',2,'p_expressao_not','parser.py',133),
  ('expressao -> ID EQUALS ID','expressao',3,'p_expressao_comparacao','parser.py',143),
  ('expressao -> ID GREATER NUMBER','expressao',3,'p_expressao_comparacao','parser.py',144),
  ('expressao -> ID LESS NUMBER','expressao',3,'p_expressao_comparacao','parser.py',145),
  ('expressao -> ID GREATER_EQUAL NUMBER','expressao',3,'p_expressao_comparacao','parser.py',146),
  ('expressao -> ID LESS_EQUAL NUMBER','expressao',3,'p_expressao_comparacao','parser.py',147),
  ('expressao -> expressao AND expressao','expressao',3,'p_expressao_logica','parser.py',158),
  ('expressao -> expressao OR expressao','expressao',3,'p_expressao_logica','parser.py',159),
]
